/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SomedayRouteImport } from './routes/someday'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogbookRouteImport } from './routes/logbook'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as AnytimeRouteImport } from './routes/anytime'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as AreaAreaIdRouteImport } from './routes/area.$areaId'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SomedayRoute = SomedayRouteImport.update({
  id: '/someday',
  path: '/someday',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbookRoute = LogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AnytimeRoute = AnytimeRouteImport.update({
  id: '/anytime',
  path: '/anytime',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAreaIdRoute = AreaAreaIdRouteImport.update({
  id: '/area/$areaId',
  path: '/area/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anytime': typeof AnytimeRoute
  '/inbox': typeof InboxRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/someday': typeof SomedayRoute
  '/tags': typeof TagsRoute
  '/today': typeof TodayRoute
  '/trash': typeof TrashRoute
  '/upcoming': typeof UpcomingRoute
  '/api/$': typeof ApiSplatRoute
  '/area/$areaId': typeof AreaAreaIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anytime': typeof AnytimeRoute
  '/inbox': typeof InboxRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/someday': typeof SomedayRoute
  '/tags': typeof TagsRoute
  '/today': typeof TodayRoute
  '/trash': typeof TrashRoute
  '/upcoming': typeof UpcomingRoute
  '/api/$': typeof ApiSplatRoute
  '/area/$areaId': typeof AreaAreaIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anytime': typeof AnytimeRoute
  '/inbox': typeof InboxRoute
  '/logbook': typeof LogbookRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/someday': typeof SomedayRoute
  '/tags': typeof TagsRoute
  '/today': typeof TodayRoute
  '/trash': typeof TrashRoute
  '/upcoming': typeof UpcomingRoute
  '/api/$': typeof ApiSplatRoute
  '/area/$areaId': typeof AreaAreaIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anytime'
    | '/inbox'
    | '/logbook'
    | '/login'
    | '/register'
    | '/someday'
    | '/tags'
    | '/today'
    | '/trash'
    | '/upcoming'
    | '/api/$'
    | '/area/$areaId'
    | '/project/$projectId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anytime'
    | '/inbox'
    | '/logbook'
    | '/login'
    | '/register'
    | '/someday'
    | '/tags'
    | '/today'
    | '/trash'
    | '/upcoming'
    | '/api/$'
    | '/area/$areaId'
    | '/project/$projectId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anytime'
    | '/inbox'
    | '/logbook'
    | '/login'
    | '/register'
    | '/someday'
    | '/tags'
    | '/today'
    | '/trash'
    | '/upcoming'
    | '/api/$'
    | '/area/$areaId'
    | '/project/$projectId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnytimeRoute: typeof AnytimeRoute
  InboxRoute: typeof InboxRoute
  LogbookRoute: typeof LogbookRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SomedayRoute: typeof SomedayRoute
  TagsRoute: typeof TagsRoute
  TodayRoute: typeof TodayRoute
  TrashRoute: typeof TrashRoute
  UpcomingRoute: typeof UpcomingRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AreaAreaIdRoute: typeof AreaAreaIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/someday': {
      id: '/someday'
      path: '/someday'
      fullPath: '/someday'
      preLoaderRoute: typeof SomedayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logbook': {
      id: '/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof LogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anytime': {
      id: '/anytime'
      path: '/anytime'
      fullPath: '/anytime'
      preLoaderRoute: typeof AnytimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/$areaId': {
      id: '/area/$areaId'
      path: '/area/$areaId'
      fullPath: '/area/$areaId'
      preLoaderRoute: typeof AreaAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnytimeRoute: AnytimeRoute,
  InboxRoute: InboxRoute,
  LogbookRoute: LogbookRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SomedayRoute: SomedayRoute,
  TagsRoute: TagsRoute,
  TodayRoute: TodayRoute,
  TrashRoute: TrashRoute,
  UpcomingRoute: UpcomingRoute,
  ApiSplatRoute: ApiSplatRoute,
  AreaAreaIdRoute: AreaAreaIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
